extends: ["@commitlint/config-conventional"]

rules:
  # Rule values are of the form [<level>, <always/never>, [<value>]].
  # Levels: 0 (disable), 1 (warning), 2 (error).
  header-max-length: [2, always, 72]
  body-max-line-length: [2, always, 72]
  footer-max-line-length: [2, always, 72]

  body-leading-blank: [2, always]
  footer-leading-blank: [2, always]
