site_name: "shplot"
site_url: "https://jkoushik.me/shplot-old"
repo_url: "https://github.com/jayanthkoushik/shplot-old"
site_description: "Documentation for Python package 'shplot'."
site_author: "Jayanth Koushik"
copyright: "Copyright (c) 2024 Jayanth Koushik"

docs_dir: "www/src"
site_dir: "www/_site"

nav:
  - "Home": "index.md"
  - "Usage":
      - "shplot": "usage/shplot.md"
      - "shplot.profiles": "usage/shplot.profiles.md"
      - "shplot.profiles.builtin": "usage/shplot.profiles.builtin.md"

plugins:
  - search
  - offline
  - mike:
      canonical_version: "latest"
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            filters:
              - "!^_"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: "#"

extra:
  version:
    provider: mike

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.expand
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
