name: Run pre-commit checks

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
