name: Build and deploy project webiste

on:
  push:
    paths:
    - 'shplot/**.py'
    - 'www/**'
    - 'README.md'
    - '.github/workflows/build-site.yml'
    - 'mkdocs.yml'
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install poetry
      run: pipx install poetry
    - name: Install build dependencies
      run: poetry install --only dev
    - name: Configure git
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: Get latest tag
      id: tag
      run: echo "tag=$( git describe --tags --abbrev=0 )" >> $GITHUB_OUTPUT
    - name: Extract major and minor version numbers
      id: version
      run: echo "version=$( echo ${{ steps.tag.outputs.tag }} | sed -E 's/^v([0-9]+)\.([0-9]+)\..*$/\1.\2/' )" >> $GITHUB_OUTPUT
    - name: Deploy website with 'mike'
      run: |
        poetry run mike set-default --allow-undefined latest
        poetry run mike deploy --update-aliases --push --allow-empty ${{ steps.version.outputs.version }} latest
