name: Check pull request

on: pull_request

jobs:
  run-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - run: poetry install --all-extras
      - run: SKIP=test poetry run pre-commit run --all-files
      - id: get-pr-commits
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "${{ steps.get-pr-commits.commits }}"

  call-run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      fail-fast: false
