name: Check pull request

on: pull_request

jobs:
  run-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - run: poetry install --all-extras
      - run: SKIP=test poetry run pre-commit run --all-files
      - id: pr-num
        name: Get pr number
        run: echo "prnum=$( echo ${{ github.ref__name }} | cut -d/ -f1 )" >> $GITHUB_OUTPUT
      - name: Verify commit messages
        run: ./scripts/verify_pr_commits.py

  call-run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      fail-fast: false
