name: Publish project to pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Create lock file
      run: poetry lock
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - name: Install build dependencies
      run: poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Build dist
      run: poetry build
    - name: Publish to pypi
      run: poetry publish -u __token__ -p $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
