name: Create and publish a new release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v4
    - name: Configure git
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Build new version
      run: npx standard-version -a
    - name: Push new commit with tag
      run: git push --follow-tags origin master
    - name: Create GitHub release
      run: npx conventional-github-releaser -p angular
      env:
        CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.RELEASE_ACCESS_TOKEN }}
