name: Create and publish a new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: >
          Version for new release. Should be a valid semvar version,
          or one of 'major', 'minor', or 'patch'. If not provided,
          version is determined automatically from commits since the
          previous release.
        type: string
        required: false
        default: ""
      pre-release:
        description: Make a pre-release.
        type: boolean
        required: false
        default: false
      pre-release-tag:
        description: >
          Optional pre-release tag. This only has effect
          if making a pre-release, and will create release
          '<major>.<minor>.<patch>-<pre-release-tag>-<pre-release-version>'.
        type: string
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies with poetry
        run: |
          poetry lock
          poetry install --only main --all-extras
      - name: Run tests
        run: poetry run python -m unittest -v

  create-release:
    runs-on: ubuntu-latest
    needs: run-test-matrix
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v4

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: poetry
      - name: Install dependencies with poetry
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --all-extras

      - name: Run pre-commit checks
        run: SKIP=test poetry run pre-commit run --all-files

      - name: Configure git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Bump version and create changelog
        run: >
          ./scripts/commit_and_tag_version.py
          -r ${{ inputs.version }}
          -p ${{ inputs.pre-release }}
          -t ${{ inputs.pre-release-tag }}

      - name: Push new version to master
        run: git push --follow-tags origin master

      - name: Create github release for new version
        run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.RELEASE_ACCESS_TOKEN }}

      - name: Create python build of new release
        run: poetry build

      #- name: Upload new release to pypi
      #  run: poetry publish -u __token__ -p $PYPI_TOKEN

      - name: Get latest git tag
        id: tag
        run: echo "tag=$( git describe --tags --abbrev=0 )" >> $GITHUB_OUTPUT
      - name: Extract major and minor versions of latest release
        id: version
        run: echo "version=$( echo ${{ steps.tag.outputs.tag }} | sed -E 's/^v([0-9]+)\.([0-9]+)\..*$/\1.\2/' )" >> $GITHUB_OUTPUT
      - name: Publish site for new release
        run: |
          poetry run mike set-default --allow-undefined latest
          poetry run mike deploy --update-aliases --push --allow-empty ${{ steps.version.outputs.version }} latest
