name: Create and publish a new release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
    - name: Configure git
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: Build new version
      run: npx standard-version -a
    - name: Push new commit with tag
      run: git push --folow-tags origin master
