name: Run project tests

on:
  push:
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/tests-run.yml'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Create lock file
      run: poetry lock
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
    - name: Install dependencies
      run: poetry install --only main --all-extras
    - name: Run tests
      run: poetry run python -m unittest -v
