name: Update pre-commit hooks

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 1 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install pre-commit
      - run: pre-commit autoupdate
      - uses: peter-evans/create-pull-request@v6
        with:
          #token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          commit-message: "chore: update pre-commit hooks"
          branch: update-pre-commit-hooks
          title: Update pre-commit hooks
          labels: automated,chore
